/*
 * generated by Xtext
 */
package org.nordakademie.mwi.tickets.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractTicketsValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(org.nordakademie.mwi.tickets.tickets.TicketsPackage.eINSTANCE);
		return result;
	}
}
