/**
 * generated by Xtext
 */
package org.nordakademie.mwi.tickets.validation;

import org.nordakademie.mwi.tickets.validation.AbstractTicketsValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class TicketsValidator extends AbstractTicketsValidator {
}
