/*
* generated by Xtext
*/
package org.nordakademie.mwi.tickets.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class TicketsAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("org/nordakademie/mwi/tickets/parser/antlr/internal/InternalTickets.tokens");
	}
}
