/*
 * generated by Xtext
 */
package org.nordakademie.mwi.tickets.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.nordakademie.mwi.tickets.ui.internal.TicketsActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class TicketsExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return TicketsActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return TicketsActivator.getInstance().getInjector(TicketsActivator.ORG_NORDAKADEMIE_MWI_TICKETS_TICKETS);
	}
	
}
