/*
 * generated by Xtext
 */
package org.nordakademie.mwi.tickets.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class TicketsUiModule extends org.nordakademie.mwi.tickets.ui.AbstractTicketsUiModule {
	public TicketsUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
