/*
* generated by Xtext
*/
package org.nordakademie.mwi.tickets;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class TicketsStandaloneSetup extends TicketsStandaloneSetupGenerated{

	public static void doSetup() {
		new TicketsStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

