/*
 * generated by Xtext
 */
package org.nordakademie.mwi.tickets;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class TicketsRuntimeModule extends org.nordakademie.mwi.tickets.AbstractTicketsRuntimeModule {

}
