grammar org.nordakademie.mwi.tickets.Tickets with org.eclipse.xtext.common.Terminals

generate tickets "http://www.nordakademie.org/mwi/tickets/TicketFields"

State:
	'state' name=STRING description=STRING ';';

Flow:
	'flow' name=STRING '{'
	states+=State* ';'
	'}';

Field:
	'field' name=STRING (fieldType=FieldType | fieldEnum=Enum | fieldFlow=Flow) ';';

enum FieldType:
	user | string | date | dateTime | int | decimal;

Enum:
	name+=STRING (',' name+=STRING)*;
	

		