/*
 * generated by Xtext
 */
package org.nordakademie.mwi.tickets.ui.contentassist

import org.nordakademie.mwi.tickets.ui.contentassist.AbstractTicketsProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class TicketsProposalProvider extends AbstractTicketsProposalProvider {
}
