/*
* generated by Xtext
*/
package org.nordakademie.mwi.tickets.services;

import com.google.inject.Singleton;
import com.google.inject.Inject;

import java.util.List;

import org.eclipse.xtext.*;
import org.eclipse.xtext.service.GrammarProvider;
import org.eclipse.xtext.service.AbstractElementFinder.*;

import org.eclipse.xtext.common.services.TerminalsGrammarAccess;

@Singleton
public class TicketsGrammarAccess extends AbstractGrammarElementFinder {
	
	
	public class TicketSystemElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "TicketSystem");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Assignment cStatesAssignment_0 = (Assignment)cAlternatives.eContents().get(0);
		private final RuleCall cStatesStateParserRuleCall_0_0 = (RuleCall)cStatesAssignment_0.eContents().get(0);
		private final Assignment cFlowsAssignment_1 = (Assignment)cAlternatives.eContents().get(1);
		private final RuleCall cFlowsFlowParserRuleCall_1_0 = (RuleCall)cFlowsAssignment_1.eContents().get(0);
		private final Assignment cFieldsAssignment_2 = (Assignment)cAlternatives.eContents().get(2);
		private final RuleCall cFieldsFieldParserRuleCall_2_0 = (RuleCall)cFieldsAssignment_2.eContents().get(0);
		private final Assignment cCategoriesAssignment_3 = (Assignment)cAlternatives.eContents().get(3);
		private final RuleCall cCategoriesTicketCategoryParserRuleCall_3_0 = (RuleCall)cCategoriesAssignment_3.eContents().get(0);
		private final Assignment cRolesAssignment_4 = (Assignment)cAlternatives.eContents().get(4);
		private final RuleCall cRolesRoleParserRuleCall_4_0 = (RuleCall)cRolesAssignment_4.eContents().get(0);
		
		//TicketSystem:
		//	(states+=State | flows+=Flow | fields+=Field | categories+=TicketCategory | roles+=Role)*;
		public ParserRule getRule() { return rule; }

		//(states+=State | flows+=Flow | fields+=Field | categories+=TicketCategory | roles+=Role)*
		public Alternatives getAlternatives() { return cAlternatives; }

		//states+=State
		public Assignment getStatesAssignment_0() { return cStatesAssignment_0; }

		//State
		public RuleCall getStatesStateParserRuleCall_0_0() { return cStatesStateParserRuleCall_0_0; }

		//flows+=Flow
		public Assignment getFlowsAssignment_1() { return cFlowsAssignment_1; }

		//Flow
		public RuleCall getFlowsFlowParserRuleCall_1_0() { return cFlowsFlowParserRuleCall_1_0; }

		//fields+=Field
		public Assignment getFieldsAssignment_2() { return cFieldsAssignment_2; }

		//Field
		public RuleCall getFieldsFieldParserRuleCall_2_0() { return cFieldsFieldParserRuleCall_2_0; }

		//categories+=TicketCategory
		public Assignment getCategoriesAssignment_3() { return cCategoriesAssignment_3; }

		//TicketCategory
		public RuleCall getCategoriesTicketCategoryParserRuleCall_3_0() { return cCategoriesTicketCategoryParserRuleCall_3_0; }

		//roles+=Role
		public Assignment getRolesAssignment_4() { return cRolesAssignment_4; }

		//Role
		public RuleCall getRolesRoleParserRuleCall_4_0() { return cRolesRoleParserRuleCall_4_0; }
	}

	public class StateElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "State");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cStateKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameQualifiedNameParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Assignment cDescriptionAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cDescriptionSTRINGTerminalRuleCall_2_0 = (RuleCall)cDescriptionAssignment_2.eContents().get(0);
		private final Keyword cSemicolonKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//State:
		//	"state" name=QualifiedName description=STRING ";";
		public ParserRule getRule() { return rule; }

		//"state" name=QualifiedName description=STRING ";"
		public Group getGroup() { return cGroup; }

		//"state"
		public Keyword getStateKeyword_0() { return cStateKeyword_0; }

		//name=QualifiedName
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//QualifiedName
		public RuleCall getNameQualifiedNameParserRuleCall_1_0() { return cNameQualifiedNameParserRuleCall_1_0; }

		//description=STRING
		public Assignment getDescriptionAssignment_2() { return cDescriptionAssignment_2; }

		//STRING
		public RuleCall getDescriptionSTRINGTerminalRuleCall_2_0() { return cDescriptionSTRINGTerminalRuleCall_2_0; }

		//";"
		public Keyword getSemicolonKeyword_3() { return cSemicolonKeyword_3; }
	}

	public class FlowElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Flow");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cFlowKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameQualifiedNameParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cStatesAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final CrossReference cStatesStateCrossReference_3_0 = (CrossReference)cStatesAssignment_3.eContents().get(0);
		private final RuleCall cStatesStateQualifiedNameParserRuleCall_3_0_1 = (RuleCall)cStatesStateCrossReference_3_0.eContents().get(1);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cCommaKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cStatesAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final CrossReference cStatesStateCrossReference_4_1_0 = (CrossReference)cStatesAssignment_4_1.eContents().get(0);
		private final RuleCall cStatesStateQualifiedNameParserRuleCall_4_1_0_1 = (RuleCall)cStatesStateCrossReference_4_1_0.eContents().get(1);
		private final Keyword cSemicolonKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//Flow:
		//	"flow" name=QualifiedName "{" states+=[State|QualifiedName] ("," states+=[State|QualifiedName])* ";" "}";
		public ParserRule getRule() { return rule; }

		//"flow" name=QualifiedName "{" states+=[State|QualifiedName] ("," states+=[State|QualifiedName])* ";" "}"
		public Group getGroup() { return cGroup; }

		//"flow"
		public Keyword getFlowKeyword_0() { return cFlowKeyword_0; }

		//name=QualifiedName
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//QualifiedName
		public RuleCall getNameQualifiedNameParserRuleCall_1_0() { return cNameQualifiedNameParserRuleCall_1_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//states+=[State|QualifiedName]
		public Assignment getStatesAssignment_3() { return cStatesAssignment_3; }

		//[State|QualifiedName]
		public CrossReference getStatesStateCrossReference_3_0() { return cStatesStateCrossReference_3_0; }

		//QualifiedName
		public RuleCall getStatesStateQualifiedNameParserRuleCall_3_0_1() { return cStatesStateQualifiedNameParserRuleCall_3_0_1; }

		//("," states+=[State|QualifiedName])*
		public Group getGroup_4() { return cGroup_4; }

		//","
		public Keyword getCommaKeyword_4_0() { return cCommaKeyword_4_0; }

		//states+=[State|QualifiedName]
		public Assignment getStatesAssignment_4_1() { return cStatesAssignment_4_1; }

		//[State|QualifiedName]
		public CrossReference getStatesStateCrossReference_4_1_0() { return cStatesStateCrossReference_4_1_0; }

		//QualifiedName
		public RuleCall getStatesStateQualifiedNameParserRuleCall_4_1_0_1() { return cStatesStateQualifiedNameParserRuleCall_4_1_0_1; }

		//";"
		public Keyword getSemicolonKeyword_5() { return cSemicolonKeyword_5; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}

	public class FieldElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Field");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cFieldKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameQualifiedNameParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Assignment cLabelAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cLabelSTRINGTerminalRuleCall_2_0 = (RuleCall)cLabelAssignment_2.eContents().get(0);
		private final Alternatives cAlternatives_3 = (Alternatives)cGroup.eContents().get(3);
		private final Assignment cFieldTypeAssignment_3_0 = (Assignment)cAlternatives_3.eContents().get(0);
		private final RuleCall cFieldTypeFieldTypeEnumRuleCall_3_0_0 = (RuleCall)cFieldTypeAssignment_3_0.eContents().get(0);
		private final Assignment cFieldEnumAssignment_3_1 = (Assignment)cAlternatives_3.eContents().get(1);
		private final RuleCall cFieldEnumEnumParserRuleCall_3_1_0 = (RuleCall)cFieldEnumAssignment_3_1.eContents().get(0);
		private final Keyword cSemicolonKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//Field:
		//	"field" name=QualifiedName label=STRING (fieldType=FieldType | fieldEnum=Enum) ";";
		public ParserRule getRule() { return rule; }

		//"field" name=QualifiedName label=STRING (fieldType=FieldType | fieldEnum=Enum) ";"
		public Group getGroup() { return cGroup; }

		//"field"
		public Keyword getFieldKeyword_0() { return cFieldKeyword_0; }

		//name=QualifiedName
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//QualifiedName
		public RuleCall getNameQualifiedNameParserRuleCall_1_0() { return cNameQualifiedNameParserRuleCall_1_0; }

		//label=STRING
		public Assignment getLabelAssignment_2() { return cLabelAssignment_2; }

		//STRING
		public RuleCall getLabelSTRINGTerminalRuleCall_2_0() { return cLabelSTRINGTerminalRuleCall_2_0; }

		//fieldType=FieldType | fieldEnum=Enum
		public Alternatives getAlternatives_3() { return cAlternatives_3; }

		//fieldType=FieldType
		public Assignment getFieldTypeAssignment_3_0() { return cFieldTypeAssignment_3_0; }

		//FieldType
		public RuleCall getFieldTypeFieldTypeEnumRuleCall_3_0_0() { return cFieldTypeFieldTypeEnumRuleCall_3_0_0; }

		//fieldEnum=Enum
		public Assignment getFieldEnumAssignment_3_1() { return cFieldEnumAssignment_3_1; }

		//Enum
		public RuleCall getFieldEnumEnumParserRuleCall_3_1_0() { return cFieldEnumEnumParserRuleCall_3_1_0; }

		//";"
		public Keyword getSemicolonKeyword_4() { return cSemicolonKeyword_4; }
	}

	public class EnumElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Enum");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cOptionAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cOptionSTRINGTerminalRuleCall_0_0 = (RuleCall)cOptionAssignment_0.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cCommaKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Assignment cOptionAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cOptionSTRINGTerminalRuleCall_1_1_0 = (RuleCall)cOptionAssignment_1_1.eContents().get(0);
		private final Keyword cSemicolonKeyword_2 = (Keyword)cGroup.eContents().get(2);
		
		//Enum:
		//	option+=STRING ("," option+=STRING)* ";";
		public ParserRule getRule() { return rule; }

		//option+=STRING ("," option+=STRING)* ";"
		public Group getGroup() { return cGroup; }

		//option+=STRING
		public Assignment getOptionAssignment_0() { return cOptionAssignment_0; }

		//STRING
		public RuleCall getOptionSTRINGTerminalRuleCall_0_0() { return cOptionSTRINGTerminalRuleCall_0_0; }

		//("," option+=STRING)*
		public Group getGroup_1() { return cGroup_1; }

		//","
		public Keyword getCommaKeyword_1_0() { return cCommaKeyword_1_0; }

		//option+=STRING
		public Assignment getOptionAssignment_1_1() { return cOptionAssignment_1_1; }

		//STRING
		public RuleCall getOptionSTRINGTerminalRuleCall_1_1_0() { return cOptionSTRINGTerminalRuleCall_1_1_0; }

		//";"
		public Keyword getSemicolonKeyword_2() { return cSemicolonKeyword_2; }
	}

	public class TicketCategoryElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "TicketCategory");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cTicketCategoryKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameQualifiedNameParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Assignment cDescriptionAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cDescriptionSTRINGTerminalRuleCall_2_0 = (RuleCall)cDescriptionAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cFlowAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final CrossReference cFlowFlowCrossReference_4_0 = (CrossReference)cFlowAssignment_4.eContents().get(0);
		private final RuleCall cFlowFlowQualifiedNameParserRuleCall_4_0_1 = (RuleCall)cFlowFlowCrossReference_4_0.eContents().get(1);
		private final Keyword cSemicolonKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cFieldsAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final CrossReference cFieldsFieldCrossReference_6_0 = (CrossReference)cFieldsAssignment_6.eContents().get(0);
		private final RuleCall cFieldsFieldQualifiedNameParserRuleCall_6_0_1 = (RuleCall)cFieldsFieldCrossReference_6_0.eContents().get(1);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cCommaKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cFieldsAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final CrossReference cFieldsFieldCrossReference_7_1_0 = (CrossReference)cFieldsAssignment_7_1.eContents().get(0);
		private final RuleCall cFieldsFieldQualifiedNameParserRuleCall_7_1_0_1 = (RuleCall)cFieldsFieldCrossReference_7_1_0.eContents().get(1);
		private final Keyword cSemicolonKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Keyword cRightCurlyBracketKeyword_9 = (Keyword)cGroup.eContents().get(9);
		
		//TicketCategory:
		//	"ticketCategory" name=QualifiedName description=STRING "{" flow=[Flow|QualifiedName] ";"
		//	fields+=[Field|QualifiedName] ("," fields+=[Field|QualifiedName])* ";" "}";
		public ParserRule getRule() { return rule; }

		//"ticketCategory" name=QualifiedName description=STRING "{" flow=[Flow|QualifiedName] ";" fields+=[Field|QualifiedName]
		//("," fields+=[Field|QualifiedName])* ";" "}"
		public Group getGroup() { return cGroup; }

		//"ticketCategory"
		public Keyword getTicketCategoryKeyword_0() { return cTicketCategoryKeyword_0; }

		//name=QualifiedName
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//QualifiedName
		public RuleCall getNameQualifiedNameParserRuleCall_1_0() { return cNameQualifiedNameParserRuleCall_1_0; }

		//description=STRING
		public Assignment getDescriptionAssignment_2() { return cDescriptionAssignment_2; }

		//STRING
		public RuleCall getDescriptionSTRINGTerminalRuleCall_2_0() { return cDescriptionSTRINGTerminalRuleCall_2_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }

		//flow=[Flow|QualifiedName]
		public Assignment getFlowAssignment_4() { return cFlowAssignment_4; }

		//[Flow|QualifiedName]
		public CrossReference getFlowFlowCrossReference_4_0() { return cFlowFlowCrossReference_4_0; }

		//QualifiedName
		public RuleCall getFlowFlowQualifiedNameParserRuleCall_4_0_1() { return cFlowFlowQualifiedNameParserRuleCall_4_0_1; }

		//";"
		public Keyword getSemicolonKeyword_5() { return cSemicolonKeyword_5; }

		//fields+=[Field|QualifiedName]
		public Assignment getFieldsAssignment_6() { return cFieldsAssignment_6; }

		//[Field|QualifiedName]
		public CrossReference getFieldsFieldCrossReference_6_0() { return cFieldsFieldCrossReference_6_0; }

		//QualifiedName
		public RuleCall getFieldsFieldQualifiedNameParserRuleCall_6_0_1() { return cFieldsFieldQualifiedNameParserRuleCall_6_0_1; }

		//("," fields+=[Field|QualifiedName])*
		public Group getGroup_7() { return cGroup_7; }

		//","
		public Keyword getCommaKeyword_7_0() { return cCommaKeyword_7_0; }

		//fields+=[Field|QualifiedName]
		public Assignment getFieldsAssignment_7_1() { return cFieldsAssignment_7_1; }

		//[Field|QualifiedName]
		public CrossReference getFieldsFieldCrossReference_7_1_0() { return cFieldsFieldCrossReference_7_1_0; }

		//QualifiedName
		public RuleCall getFieldsFieldQualifiedNameParserRuleCall_7_1_0_1() { return cFieldsFieldQualifiedNameParserRuleCall_7_1_0_1; }

		//";"
		public Keyword getSemicolonKeyword_8() { return cSemicolonKeyword_8; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_9() { return cRightCurlyBracketKeyword_9; }
	}

	public class RoleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Role");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cRoleKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameQualifiedNameParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Assignment cDescriptionAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cDescriptionSTRINGTerminalRuleCall_2_0 = (RuleCall)cDescriptionAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Assignment cFieldsAssignment_4_0 = (Assignment)cGroup_4.eContents().get(0);
		private final CrossReference cFieldsFieldCrossReference_4_0_0 = (CrossReference)cFieldsAssignment_4_0.eContents().get(0);
		private final RuleCall cFieldsFieldQualifiedNameParserRuleCall_4_0_0_1 = (RuleCall)cFieldsFieldCrossReference_4_0_0.eContents().get(1);
		private final Assignment cPermissionAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cPermissionPermissionEnumRuleCall_4_1_0 = (RuleCall)cPermissionAssignment_4_1.eContents().get(0);
		private final Keyword cSemicolonKeyword_4_2 = (Keyword)cGroup_4.eContents().get(2);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Role:
		//	"role" name=QualifiedName description=STRING "{" (fields+=[Field|QualifiedName] permission+=Permission ";")* "}";
		public ParserRule getRule() { return rule; }

		//"role" name=QualifiedName description=STRING "{" (fields+=[Field|QualifiedName] permission+=Permission ";")* "}"
		public Group getGroup() { return cGroup; }

		//"role"
		public Keyword getRoleKeyword_0() { return cRoleKeyword_0; }

		//name=QualifiedName
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//QualifiedName
		public RuleCall getNameQualifiedNameParserRuleCall_1_0() { return cNameQualifiedNameParserRuleCall_1_0; }

		//description=STRING
		public Assignment getDescriptionAssignment_2() { return cDescriptionAssignment_2; }

		//STRING
		public RuleCall getDescriptionSTRINGTerminalRuleCall_2_0() { return cDescriptionSTRINGTerminalRuleCall_2_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }

		//(fields+=[Field|QualifiedName] permission+=Permission ";")*
		public Group getGroup_4() { return cGroup_4; }

		//fields+=[Field|QualifiedName]
		public Assignment getFieldsAssignment_4_0() { return cFieldsAssignment_4_0; }

		//[Field|QualifiedName]
		public CrossReference getFieldsFieldCrossReference_4_0_0() { return cFieldsFieldCrossReference_4_0_0; }

		//QualifiedName
		public RuleCall getFieldsFieldQualifiedNameParserRuleCall_4_0_0_1() { return cFieldsFieldQualifiedNameParserRuleCall_4_0_0_1; }

		//permission+=Permission
		public Assignment getPermissionAssignment_4_1() { return cPermissionAssignment_4_1; }

		//Permission
		public RuleCall getPermissionPermissionEnumRuleCall_4_1_0() { return cPermissionPermissionEnumRuleCall_4_1_0; }

		//";"
		public Keyword getSemicolonKeyword_4_2() { return cSemicolonKeyword_4_2; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}

	public class QualifiedNameElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "QualifiedName");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cIDTerminalRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cFullStopKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1_1 = (RuleCall)cGroup_1.eContents().get(1);
		
		//QualifiedName:
		//	ID ("." ID)*;
		public ParserRule getRule() { return rule; }

		//ID ("." ID)*
		public Group getGroup() { return cGroup; }

		//ID
		public RuleCall getIDTerminalRuleCall_0() { return cIDTerminalRuleCall_0; }

		//("." ID)*
		public Group getGroup_1() { return cGroup_1; }

		//"."
		public Keyword getFullStopKeyword_1_0() { return cFullStopKeyword_1_0; }

		//ID
		public RuleCall getIDTerminalRuleCall_1_1() { return cIDTerminalRuleCall_1_1; }
	}
	
	
	public class PermissionElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "Permission");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cCreateEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cCreateCreateKeyword_0_0 = (Keyword)cCreateEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cReadEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cReadReadKeyword_1_0 = (Keyword)cReadEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cModifyEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cModifyModifyKeyword_2_0 = (Keyword)cModifyEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cDeleteEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cDeleteDeleteKeyword_3_0 = (Keyword)cDeleteEnumLiteralDeclaration_3.eContents().get(0);
		
		//enum Permission:
		//	create | read | modify | delete;
		public EnumRule getRule() { return rule; }

		//create | read | modify | delete
		public Alternatives getAlternatives() { return cAlternatives; }

		//create
		public EnumLiteralDeclaration getCreateEnumLiteralDeclaration_0() { return cCreateEnumLiteralDeclaration_0; }

		//"create"
		public Keyword getCreateCreateKeyword_0_0() { return cCreateCreateKeyword_0_0; }

		//read
		public EnumLiteralDeclaration getReadEnumLiteralDeclaration_1() { return cReadEnumLiteralDeclaration_1; }

		//"read"
		public Keyword getReadReadKeyword_1_0() { return cReadReadKeyword_1_0; }

		//modify
		public EnumLiteralDeclaration getModifyEnumLiteralDeclaration_2() { return cModifyEnumLiteralDeclaration_2; }

		//"modify"
		public Keyword getModifyModifyKeyword_2_0() { return cModifyModifyKeyword_2_0; }

		//delete
		public EnumLiteralDeclaration getDeleteEnumLiteralDeclaration_3() { return cDeleteEnumLiteralDeclaration_3; }

		//"delete"
		public Keyword getDeleteDeleteKeyword_3_0() { return cDeleteDeleteKeyword_3_0; }
	}

	public class FieldTypeElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "FieldType");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cUserEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cUserUserKeyword_0_0 = (Keyword)cUserEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cStringEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cStringStringKeyword_1_0 = (Keyword)cStringEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cDateEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cDateDateKeyword_2_0 = (Keyword)cDateEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cDateTimeEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cDateTimeDateTimeKeyword_3_0 = (Keyword)cDateTimeEnumLiteralDeclaration_3.eContents().get(0);
		private final EnumLiteralDeclaration cIntEnumLiteralDeclaration_4 = (EnumLiteralDeclaration)cAlternatives.eContents().get(4);
		private final Keyword cIntIntKeyword_4_0 = (Keyword)cIntEnumLiteralDeclaration_4.eContents().get(0);
		private final EnumLiteralDeclaration cDecimalEnumLiteralDeclaration_5 = (EnumLiteralDeclaration)cAlternatives.eContents().get(5);
		private final Keyword cDecimalDecimalKeyword_5_0 = (Keyword)cDecimalEnumLiteralDeclaration_5.eContents().get(0);
		
		//enum FieldType:
		//	user | string | date | dateTime | int | decimal;
		public EnumRule getRule() { return rule; }

		//user | string | date | dateTime | int | decimal
		public Alternatives getAlternatives() { return cAlternatives; }

		//user
		public EnumLiteralDeclaration getUserEnumLiteralDeclaration_0() { return cUserEnumLiteralDeclaration_0; }

		//"user"
		public Keyword getUserUserKeyword_0_0() { return cUserUserKeyword_0_0; }

		//string
		public EnumLiteralDeclaration getStringEnumLiteralDeclaration_1() { return cStringEnumLiteralDeclaration_1; }

		//"string"
		public Keyword getStringStringKeyword_1_0() { return cStringStringKeyword_1_0; }

		//date
		public EnumLiteralDeclaration getDateEnumLiteralDeclaration_2() { return cDateEnumLiteralDeclaration_2; }

		//"date"
		public Keyword getDateDateKeyword_2_0() { return cDateDateKeyword_2_0; }

		//dateTime
		public EnumLiteralDeclaration getDateTimeEnumLiteralDeclaration_3() { return cDateTimeEnumLiteralDeclaration_3; }

		//"dateTime"
		public Keyword getDateTimeDateTimeKeyword_3_0() { return cDateTimeDateTimeKeyword_3_0; }

		//int
		public EnumLiteralDeclaration getIntEnumLiteralDeclaration_4() { return cIntEnumLiteralDeclaration_4; }

		//"int"
		public Keyword getIntIntKeyword_4_0() { return cIntIntKeyword_4_0; }

		//decimal
		public EnumLiteralDeclaration getDecimalEnumLiteralDeclaration_5() { return cDecimalEnumLiteralDeclaration_5; }

		//"decimal"
		public Keyword getDecimalDecimalKeyword_5_0() { return cDecimalDecimalKeyword_5_0; }
	}
	
	private final TicketSystemElements pTicketSystem;
	private final StateElements pState;
	private final FlowElements pFlow;
	private final FieldElements pField;
	private final EnumElements pEnum;
	private final TicketCategoryElements pTicketCategory;
	private final RoleElements pRole;
	private final PermissionElements unknownRulePermission;
	private final FieldTypeElements unknownRuleFieldType;
	private final QualifiedNameElements pQualifiedName;
	
	private final Grammar grammar;

	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public TicketsGrammarAccess(GrammarProvider grammarProvider,
		TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pTicketSystem = new TicketSystemElements();
		this.pState = new StateElements();
		this.pFlow = new FlowElements();
		this.pField = new FieldElements();
		this.pEnum = new EnumElements();
		this.pTicketCategory = new TicketCategoryElements();
		this.pRole = new RoleElements();
		this.unknownRulePermission = new PermissionElements();
		this.unknownRuleFieldType = new FieldTypeElements();
		this.pQualifiedName = new QualifiedNameElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.nordakademie.mwi.tickets.Tickets".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	
	public Grammar getGrammar() {
		return grammar;
	}
	

	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//TicketSystem:
	//	(states+=State | flows+=Flow | fields+=Field | categories+=TicketCategory | roles+=Role)*;
	public TicketSystemElements getTicketSystemAccess() {
		return pTicketSystem;
	}
	
	public ParserRule getTicketSystemRule() {
		return getTicketSystemAccess().getRule();
	}

	//State:
	//	"state" name=QualifiedName description=STRING ";";
	public StateElements getStateAccess() {
		return pState;
	}
	
	public ParserRule getStateRule() {
		return getStateAccess().getRule();
	}

	//Flow:
	//	"flow" name=QualifiedName "{" states+=[State|QualifiedName] ("," states+=[State|QualifiedName])* ";" "}";
	public FlowElements getFlowAccess() {
		return pFlow;
	}
	
	public ParserRule getFlowRule() {
		return getFlowAccess().getRule();
	}

	//Field:
	//	"field" name=QualifiedName label=STRING (fieldType=FieldType | fieldEnum=Enum) ";";
	public FieldElements getFieldAccess() {
		return pField;
	}
	
	public ParserRule getFieldRule() {
		return getFieldAccess().getRule();
	}

	//Enum:
	//	option+=STRING ("," option+=STRING)* ";";
	public EnumElements getEnumAccess() {
		return pEnum;
	}
	
	public ParserRule getEnumRule() {
		return getEnumAccess().getRule();
	}

	//TicketCategory:
	//	"ticketCategory" name=QualifiedName description=STRING "{" flow=[Flow|QualifiedName] ";"
	//	fields+=[Field|QualifiedName] ("," fields+=[Field|QualifiedName])* ";" "}";
	public TicketCategoryElements getTicketCategoryAccess() {
		return pTicketCategory;
	}
	
	public ParserRule getTicketCategoryRule() {
		return getTicketCategoryAccess().getRule();
	}

	//Role:
	//	"role" name=QualifiedName description=STRING "{" (fields+=[Field|QualifiedName] permission+=Permission ";")* "}";
	public RoleElements getRoleAccess() {
		return pRole;
	}
	
	public ParserRule getRoleRule() {
		return getRoleAccess().getRule();
	}

	//enum Permission:
	//	create | read | modify | delete;
	public PermissionElements getPermissionAccess() {
		return unknownRulePermission;
	}
	
	public EnumRule getPermissionRule() {
		return getPermissionAccess().getRule();
	}

	//enum FieldType:
	//	user | string | date | dateTime | int | decimal;
	public FieldTypeElements getFieldTypeAccess() {
		return unknownRuleFieldType;
	}
	
	public EnumRule getFieldTypeRule() {
		return getFieldTypeAccess().getRule();
	}

	//QualifiedName:
	//	ID ("." ID)*;
	public QualifiedNameElements getQualifiedNameAccess() {
		return pQualifiedName;
	}
	
	public ParserRule getQualifiedNameRule() {
		return getQualifiedNameAccess().getRule();
	}

	//terminal ID:
	//	"^"? ("a".."z" | "A".."Z" | "_") ("a".."z" | "A".."Z" | "_" | "0".."9")*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	} 

	//terminal INT returns ecore::EInt:
	//	"0".."9"+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	} 

	//terminal STRING:
	//	"\"" ("\\" . / * 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' * / | !("\\" | "\""))* "\"" | "\'" ("\\" .
	//	/ * 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' * / | !("\\" | "\'"))* "\'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	} 

	//terminal ML_COMMENT:
	//	"/ *"->"* /";
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	} 

	//terminal SL_COMMENT:
	//	"//" !("\n" | "\r")* ("\r"? "\n")?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	} 

	//terminal WS:
	//	(" " | "\t" | "\r" | "\n")+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	} 

	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	} 
}
